import type { Content } from "./types";

const B = "/figma/brands";
const P = "/figma/portfolio";

export const defaultContent: Content = {
  header: {
    brand: "EPIGROTIVE",
    brandSub: "GAMING",
    logo: "/figma/emblem.png",
    nav: [
      { label: "HOME", href: "#top" },
      { label: "ABOUT", href: "#deliver" },
      { label: "CONTACT", href: "#contact" },
    ],
    ctaHref: "#contact",
  },
  socials: [
    { name: "Instagram", href: "https://www.instagram.com/epigrotivegaming/" },
    { name: "X", href: "https://x.com/teamepigrotive" },
    { name: "YouTube", href: "https://www.youtube.com/@epigrotivegaming" },
    { name: "Discord", href: "https://discord.gg/ejajtGymDw" },
  ],
  hero: {
    eyebrow: ["ESPORTS", "GAMING", "EPIGRO MEDIA"],
    line1: "Building The Next Era Of",
    line2: "Gaming & Esports",
    sub1: "Powering the gaming ecosystem through",
    sub2: "esports, media, content and brand experiences.",
    cta: "START A PROJECT",
    ctaHref: "#contact",
    cardLine1: "One house.",
    cardLine2: "Two engines.",
    cardCta: "Explore",
  },
  engines: {
    heading1: "ONE HOUSE.",
    heading2: "TWO ENGINES.",
    mobileSubtitle: "Two engines. One standard of execution.",
    cards: [
      {
        label: "EPIGRO MEDIA",
        title1: "MAKE CULTURE",
        title2: "MOVE.",
        copy: [
          "Brand worlds, content systems and creator",
          "programs designed for the audience, not",
          "around it.",
        ],
        mobileCopy:
          "Brand worlds, content systems and creator programs designed for fan attention, not ad spend.",
        tags: ["BRAND", "CONTENT", "CREATORS"],
        mobileTags: ["Gaming", "Content", "Creators"],
        cta: "Explore media",
        href: "#deliver",
        photo: "/figma/engines/photo-media.png",
      },
      {
        label: "EPIGROTIVE GAMING",
        title1: "BUILD THE",
        title2: "ARENA.",
        copy: [
          "Esports IPs, tournaments and community",
          "ecosystems that give people a reason",
          "to show up.",
        ],
        mobileCopy:
          "Esports IPs, tournaments and community ecosystems that give people a reason to show up.",
        tags: ["ESPORTS", "TOURNAMENTS", "COMMUNITY"],
        mobileTags: ["Esports", "Tournaments", "Community"],
        cta: "Explore gaming",
        href: "#ips",
        photo: "/figma/engines/photo-gaming.png",
      },
    ],
  },
  stats: {
    eyebrow: "EPIGRO",
    line1: "NUMBERS THAT",
    line2: "DO THE TALKING.",
    sub1: "Scale isn't a headline stat — it's the proof behind every campaign and every event,",
    sub2: "measured in the audiences who show up and stay.",
    image: "/figma/stats/epig.png",
    items: [
      { value: "150+", label: "LIVE EVENTS PRODUCED" },
      { value: "40M+", label: "CUMULATIVE VIEWS GENERATED" },
      { value: "25+", label: "ACTIVE BRAND PARTNERS" },
      { value: "12", label: "ORIGINAL TOURNAMENT IPS" },
    ],
  },
  deliver: {
    heading1: "WHAT WE",
    heading2: "DELIVER.",
    subtitle: "Two engines. One standard of execution.",
    services: [
      {
        number: "01",
        title: "Event Management",
        copy: [
          "End-to-end tournament and live-event",
          "operations — from venue logistics and",
          "player ops to the run sheet that keeps",
          "show day on time.",
        ],
        mobileCopy:
          "End-to-end tournament and live-event operations — from venue logistics and player ops to the on-show day in full.",
        image: "",
        href: "#contact",
      },
      {
        number: "02",
        title: "Production",
        copy: [
          "Broadcast, stage and content production",
          "built for competitive gaming, from camera",
          "blocking to the graphics package",
          "on screen.",
        ],
        mobileCopy:
          "Broadcast, stage and content production built for competitive gaming. From camera blocking to the graphics package, on screen.",
        image: "",
        href: "#contact",
      },
      {
        number: "03",
        title: "Creatives",
        copy: [
          "Brand worlds, campaigns and design",
          "systems that give every activation a",
          "consistent, recognizable identity.",
        ],
        mobileCopy:
          "Brand worlds, campaigns and design systems that give every activation a consistent, recognizable identity.",
        image: "",
        href: "#contact",
      },
      {
        number: "04",
        title: "Influencer Marketing",
        copy: [
          "Creator programs that connect brands",
          "with audiences through the players and",
          "personalities they already trust.",
        ],
        mobileCopy:
          "Creator programs that connect brands with audiences through the players and personalities they already trust.",
        image: "",
        href: "#contact",
      },
    ],
  },
  ips: {
    heading1: "OUR IPS.",
    heading2: "EMBRACE THE CHALLENGE.",
    sub1: "Formats we've built from scratch and grow season after season — because ownership",
    sub2: "means every rule, every rivalry, and every night on stage is entirely ours.",
    items: Array.from({ length: 5 }, () => ({
      name: "Epigrotive Pro Series",
      copy: "A high-stakes competitive format built for rising teams, broadcast drama and a community that returns every season.",
      logo: "",
    })),
  },
  brands: {
    heading1: "BRANDS WE'VE",
    heading2: "WORKED WITH.",
    logos: [
      ["amazon-pay", "Amazon Pay"],
      ["amd", "AMD"],
      ["gigabyte-technology", "Gigabyte Technology"],
      ["dubai-energy-drink", "Dubai Energy Drink"],
      ["hp", "HP"],
      ["joy-e-bike", "Joy e-bike"],
      ["purple-ring-brand-unconfirmed", "Brand"],
      ["nvidia", "NVIDIA"],
      ["razer", "Razer"],
      ["rooter-shop", "Rooter Shop"],
      ["rooter", "Rooter"],
      ["the-fit-check", "The Fit Check"],
      ["blue-f-brand-unconfirmed", "Brand"],
      ["unipin", "UniPin"],
      ["vedam-school-of-technology", "Vedam School of Technology"],
      ["veroforza", "Veroforza"],
      ["vishal-peripherals", "Vishal Peripherals"],
      ["wellversed", "Wellversed"],
    ].map(([f, alt]) => ({ src: `${B}/${f}.png`, alt })),
  },
  portfolio: {
    heading1: "A SELECTION OF",
    heading2: "PORTFOLIO",
    exploreLabel: "EXPLORE MORE",
    exploreHref: "#contact",
    marquee: ["p12", "p13", "p14", "p15", "p22", "p23", "p24", "p25"].map((f) => `${P}/${f}.png`),
    grid: [
      ["p11", "Championship jersey"],
      ["p12", "Gaming campaign"],
      ["p13", "Esports portrait"],
      ["p14", "Team uniform"],
      ["p15", "Live arena"],
      ["p21", "Event production"],
      ["p22", "Festival creative"],
      ["p23", "Merchandise drop"],
    ].map(([f, label]) => ({ src: `${P}/${f}.png`, label })),
  },
  contact: {
    eyebrow: "CONTACT",
    line1: "Let’s build",
    line2: "something",
    line3: "remarkable.",
    sub1: "If you have any questions or want to know more about",
    sub2: "our services, feel free to contact us.",
    phone: "+91 83691 23086",
    email: "manage.epigrotivegaming@gmail.com",
    formTitle: "Get in touch",
    formBlurb: "Tell us what you’re building and our team will get back to you.",
    namePlaceholder: "Your Name",
    emailPlaceholder: "Your Email",
    messagePlaceholder: "Enter Message",
    sendLabel: "SEND",
    privacy: "We respect your privacy. Your information is safe with us.",
    successMessage: "Thanks — your message was sent. We’ll get back to you shortly.",
  },
  footer: {
    brand: "EPIGROTIVE",
    brandSub: "GAMING",
    logo: "/figma/footer/emblem.png",
    copyright: "© 2026 Epigrotive Gaming. All rights reserved.",
    privacyLabel: "Privacy policy",
    nav: [
      { label: "Home", href: "#top" },
      { label: "About", href: "#engines" },
      { label: "Services", href: "#deliver" },
      { label: "Portfolio", href: "#portfolio" },
      { label: "Contact", href: "#contact" },
    ],
  },
};
